name: anime_quote
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  gif: ^2.3.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  hydrated_bloc: ^8.1.0
  mockito: ^5.3.0
  test: ^1.21.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter_icons:
  android: "launche_icon"
  ios: true
  image_path: "assets/launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/gon_waiting.gif

  fonts:
    - family: Fantasque
      fonts:
        - asset: assets/fonts/Fantasque.ttf
