name: Testing Deployment

on:
  push:
    branches: [develop]

jobs:
  build_and_deploy:
    runs-on: macos-12

    steps:
      - name: Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.3.1"
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
          
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.5"
          channel: "stable"
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5.0'
          
      - name: Update gems
        run: gem update --system

      - name: Sync dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      
      - name: Install bundle on Android directory
        working-directory: ${{ github.workspace }}/android
        run: bundle install

      - name: Install Firebase app distribution
        working-directory: ${{ github.workspace }}/android
        run: bundle exec fastlane add_plugin firebase_app_distribution

      - name: Remove duplicate classes
        working-directory: ${{ github.workspace }}/android
        run: gradle clean build

      - name: Build aab
        run: flutter build appbundle 
